// Command gentables writes text/arabic_table.go from the Unicode character
// database.
//
// The table is generated rather than transcribed because it is 76 letters with four
// forms each, and a single wrong codepoint would show up as one Arabic letter that
// silently draws in the wrong shape — the sort of mistake nobody reviewing 300 hex
// literals would catch. Everything here is read out of Unicode's own character
// names: the presentation-form blocks name each glyph "ARABIC LETTER <X> <FORM>
// FORM", so the base letter and the form come straight from the database, and the
// joining class follows from which forms exist at all.
//
// Usage: go run ./text/internal/gentables > text/arabic_table.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"

	"golang.org/x/text/unicode/runenames"
)

// The two presentation-form blocks. Forms-A carries the Persian, Urdu and Sindhi
// letters; Forms-B carries core Arabic and the lam-alef ligatures.
const (
	formsAStart = 0xFB50
	formsAEnd   = 0xFDFF
	formsBStart = 0xFE70
	formsBEnd   = 0xFEFF
)

type forms struct {
	base                             rune
	name                             string
	isolated, final, initial, medial rune
}

func (f forms) dual() bool { return f.initial != 0 && f.medial != 0 }

func main() {
	letters := map[rune]*forms{}

	for r := rune(formsAStart); r <= formsBEnd; r++ {
		if r > formsAEnd && r < formsBStart {
			continue
		}

		name := runenames.Name(r)
		base, form, ok := parseFormName(name)
		if !ok {
			continue
		}

		entry := letters[base]
		if entry == nil {
			entry = &forms{base: base, name: titleCase(name)}
			letters[base] = entry
		}
		switch form {
		case "ISOLATED":
			entry.isolated = r
		case "FINAL":
			entry.final = r
		case "INITIAL":
			entry.initial = r
		case "MEDIAL":
			entry.medial = r
		}
	}

	ordered := make([]*forms, 0, len(letters))
	for _, entry := range letters {
		ordered = append(ordered, entry)
	}
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].base < ordered[j].base })

	out := bufio.NewWriter(os.Stdout)
	defer out.Flush()

	writeHeader(out)

	fmt.Fprintf(out, "var arabicShaping = map[rune]arabicForms{\n")
	for _, entry := range ordered {
		class := "joinRight"
		if entry.dual() {
			class = "joinDual"
		}
		fmt.Fprintf(out, "\t%s: {%s, %s, %s, %s, %s}, // %s\n",
			hex(entry.base), hex(entry.isolated), hex(entry.final),
			hex(entry.initial), hex(entry.medial), class, entry.name)
	}
	fmt.Fprintf(out, "}\n")

	writeLigatures(out)
}

// parseFormName pulls the base letter and the form out of a presentation form's own
// Unicode name, reporting false for anything that is not one.
func parseFormName(name string) (base rune, form string, ok bool) {
	const prefix = "ARABIC LETTER "

	if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, " FORM") {
		return 0, "", false
	}

	fields := strings.Fields(strings.TrimSuffix(name, " FORM"))
	if len(fields) < 4 {
		return 0, "", false
	}
	form = fields[len(fields)-1]

	switch form {
	case "ISOLATED", "FINAL", "INITIAL", "MEDIAL":
	default:
		return 0, "", false
	}

	// The base letter's name is what is left once the form is taken off. Looking it
	// up by name is what ties the two together: there is no arithmetic relation
	// between a letter and its forms to get wrong.
	baseName := prefix + strings.Join(fields[2:len(fields)-1], " ")
	base, ok = lookup(baseName)
	return base, form, ok
}

// lookup finds a character by name. x/text exposes names but not the reverse
// mapping, and the Arabic blocks are small enough to scan.
func lookup(name string) (rune, bool) {
	for r := rune(0x0600); r <= 0x08FF; r++ {
		if runenames.Name(r) == name {
			return r, true
		}
	}
	return 0, false
}

// writeHeader emits the package clause and the types the table is written in terms
// of, so the generated file is self-contained and reads as ordinary Go.
func writeHeader(out *bufio.Writer) {
	fmt.Fprint(out, `package text

// Code generated by text/internal/gentables from the Unicode character database.
// DO NOT EDIT.
//
// Every entry was derived from the characters\' own Unicode names rather than
// transcribed: the presentation-form blocks name each glyph "ARABIC LETTER <X>
// <FORM> FORM", so the base letter and the form are read straight out of the
// database. The joining class follows from which forms exist — a letter with initial
// and medial forms joins on both sides, one with only isolated and final forms joins
// only to what precedes it.
//
// Regenerate with: go run ./text/internal/gentables > text/arabic_table.go

// joining describes how a letter connects to its neighbours.
type joining uint8

const (
	// joinNone is a character that neither joins nor lets its neighbours join
	// through it: a space, a digit, a full stop.
	joinNone joining = iota

	// joinRight connects only to the letter before it, so it takes a final or an
	// isolated form but never an initial or a medial one. Alef, dal, reh and waw are
	// the familiar cases, and they are why an Arabic word breaks into visual clusters
	// rather than running unbroken from one end to the other.
	joinRight

	// joinDual connects on both sides and has all four forms.
	joinDual

	// joinCausing does not change shape itself but lets its neighbours join through
	// it, which is what tatweel and the zero-width joiner are for.
	joinCausing

	// joinTransparent is skipped when working out context: a vowel mark sits above a
	// letter without interrupting the connection beneath it.
	joinTransparent
)

// arabicForms holds the four contextual forms of one letter. A right-joining letter
// leaves initial and medial zero, which the shaper reads as "no such form".
type arabicForms struct {
	isolated, final, initial, medial rune
	class                            joining
}

// arabicShaping maps a base letter to its forms. A character absent from the map is
// transparent, join-causing or non-joining; shapingClass decides which.
`)
}

func writeLigatures(out *bufio.Writer) {
	type pair struct{ isolated, final rune }

	ligatures := map[rune]*pair{}
	names := map[rune]string{}

	const prefix = "ARABIC LIGATURE LAM WITH "

	for r := rune(formsBStart); r <= formsBEnd; r++ {
		name := runenames.Name(r)
		if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, " FORM") {
			continue
		}

		rest := strings.TrimSuffix(name, " FORM")
		rest = strings.TrimPrefix(rest, prefix)

		isFinal := strings.HasSuffix(rest, "FINAL")
		rest = strings.TrimSuffix(strings.TrimSuffix(rest, "FINAL"), "ISOLATED")

		alef, ok := lookup("ARABIC LETTER " + strings.TrimSpace(rest))
		if !ok {
			continue
		}

		if ligatures[alef] == nil {
			ligatures[alef] = &pair{}
			names[alef] = titleCase(strings.TrimSpace(rest))
		}
		if isFinal {
			ligatures[alef].final = r
		} else {
			ligatures[alef].isolated = r
		}
	}

	alefs := make([]rune, 0, len(ligatures))
	for alef := range ligatures {
		alefs = append(alefs, alef)
	}
	sort.Slice(alefs, func(i, j int) bool { return alefs[i] < alefs[j] })

	fmt.Fprint(out, `
// lamAlef holds the mandatory lam-alef ligatures.
//
// These are not an optional nicety. Arabic orthography requires lam followed by alef
// to be written as one joined shape, and setting the two letters side by side is as
// wrong as putting a space inside an English word. Unicode gives each ligature its
// own codepoint in the presentation-form block, so no glyph substitution table is
// needed to reach it.
var lamAlef = map[rune]struct{ isolated, final rune }{
`)
	for _, alef := range alefs {
		p := ligatures[alef]
		fmt.Fprintf(out, "\t%s: {%s, %s}, // lam + %s\n",
			hex(alef), hex(p.isolated), hex(p.final), names[alef])
	}
	fmt.Fprintf(out, "}\n")
}

func hex(r rune) string {
	if r == 0 {
		return "0"
	}
	return fmt.Sprintf("0x%04X", r)
}

// titleCase turns a Unicode name into something readable in a trailing comment.
func titleCase(name string) string {
	name = strings.TrimPrefix(name, "ARABIC LETTER ")
	name = strings.TrimSuffix(name, " FORM")

	for _, form := range []string{" ISOLATED", " FINAL", " INITIAL", " MEDIAL"} {
		name = strings.TrimSuffix(name, form)
	}

	words := strings.Fields(strings.ToLower(name))
	for i, w := range words {
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}
