package text

// Code generated by text/internal/gentables from the Unicode character database.
// DO NOT EDIT.
//
// Every entry was derived from the characters\' own Unicode names rather than
// transcribed: the presentation-form blocks name each glyph "ARABIC LETTER <X>
// <FORM> FORM", so the base letter and the form are read straight out of the
// database. The joining class follows from which forms exist — a letter with initial
// and medial forms joins on both sides, one with only isolated and final forms joins
// only to what precedes it.
//
// Regenerate with: go run ./text/internal/gentables > text/arabic_table.go

// joining describes how a letter connects to its neighbours.
type joining uint8

const (
	// joinNone is a character that neither joins nor lets its neighbours join
	// through it: a space, a digit, a full stop.
	joinNone joining = iota

	// joinRight connects only to the letter before it, so it takes a final or an
	// isolated form but never an initial or a medial one. Alef, dal, reh and waw are
	// the familiar cases, and they are why an Arabic word breaks into visual clusters
	// rather than running unbroken from one end to the other.
	joinRight

	// joinDual connects on both sides and has all four forms.
	joinDual

	// joinCausing does not change shape itself but lets its neighbours join through
	// it, which is what tatweel and the zero-width joiner are for.
	joinCausing

	// joinTransparent is skipped when working out context: a vowel mark sits above a
	// letter without interrupting the connection beneath it.
	joinTransparent
)

// arabicForms holds the four contextual forms of one letter. A right-joining letter
// leaves initial and medial zero, which the shaper reads as "no such form".
type arabicForms struct {
	isolated, final, initial, medial rune
	class                            joining
}

// arabicShaping maps a base letter to its forms. A character absent from the map is
// transparent, join-causing or non-joining; shapingClass decides which.
var arabicShaping = map[rune]arabicForms{
	0x0621: {0xFE80, 0, 0, 0, joinRight},               // Hamza
	0x0622: {0xFE81, 0xFE82, 0, 0, joinRight},          // Alef With Madda Above
	0x0623: {0xFE83, 0xFE84, 0, 0, joinRight},          // Alef With Hamza Above
	0x0624: {0xFE85, 0xFE86, 0, 0, joinRight},          // Waw With Hamza Above
	0x0625: {0xFE87, 0xFE88, 0, 0, joinRight},          // Alef With Hamza Below
	0x0626: {0xFE89, 0xFE8A, 0xFE8B, 0xFE8C, joinDual}, // Yeh With Hamza Above
	0x0627: {0xFE8D, 0xFE8E, 0, 0, joinRight},          // Alef
	0x0628: {0xFE8F, 0xFE90, 0xFE91, 0xFE92, joinDual}, // Beh
	0x0629: {0xFE93, 0xFE94, 0, 0, joinRight},          // Teh Marbuta
	0x062A: {0xFE95, 0xFE96, 0xFE97, 0xFE98, joinDual}, // Teh
	0x062B: {0xFE99, 0xFE9A, 0xFE9B, 0xFE9C, joinDual}, // Theh
	0x062C: {0xFE9D, 0xFE9E, 0xFE9F, 0xFEA0, joinDual}, // Jeem
	0x062D: {0xFEA1, 0xFEA2, 0xFEA3, 0xFEA4, joinDual}, // Hah
	0x062E: {0xFEA5, 0xFEA6, 0xFEA7, 0xFEA8, joinDual}, // Khah
	0x062F: {0xFEA9, 0xFEAA, 0, 0, joinRight},          // Dal
	0x0630: {0xFEAB, 0xFEAC, 0, 0, joinRight},          // Thal
	0x0631: {0xFEAD, 0xFEAE, 0, 0, joinRight},          // Reh
	0x0632: {0xFEAF, 0xFEB0, 0, 0, joinRight},          // Zain
	0x0633: {0xFEB1, 0xFEB2, 0xFEB3, 0xFEB4, joinDual}, // Seen
	0x0634: {0xFEB5, 0xFEB6, 0xFEB7, 0xFEB8, joinDual}, // Sheen
	0x0635: {0xFEB9, 0xFEBA, 0xFEBB, 0xFEBC, joinDual}, // Sad
	0x0636: {0xFEBD, 0xFEBE, 0xFEBF, 0xFEC0, joinDual}, // Dad
	0x0637: {0xFEC1, 0xFEC2, 0xFEC3, 0xFEC4, joinDual}, // Tah
	0x0638: {0xFEC5, 0xFEC6, 0xFEC7, 0xFEC8, joinDual}, // Zah
	0x0639: {0xFEC9, 0xFECA, 0xFECB, 0xFECC, joinDual}, // Ain
	0x063A: {0xFECD, 0xFECE, 0xFECF, 0xFED0, joinDual}, // Ghain
	0x0641: {0xFED1, 0xFED2, 0xFED3, 0xFED4, joinDual}, // Feh
	0x0642: {0xFED5, 0xFED6, 0xFED7, 0xFED8, joinDual}, // Qaf
	0x0643: {0xFED9, 0xFEDA, 0xFEDB, 0xFEDC, joinDual}, // Kaf
	0x0644: {0xFEDD, 0xFEDE, 0xFEDF, 0xFEE0, joinDual}, // Lam
	0x0645: {0xFEE1, 0xFEE2, 0xFEE3, 0xFEE4, joinDual}, // Meem
	0x0646: {0xFEE5, 0xFEE6, 0xFEE7, 0xFEE8, joinDual}, // Noon
	0x0647: {0xFEE9, 0xFEEA, 0xFEEB, 0xFEEC, joinDual}, // Heh
	0x0648: {0xFEED, 0xFEEE, 0, 0, joinRight},          // Waw
	0x0649: {0xFEEF, 0xFEF0, 0, 0, joinRight},          // Alef Maksura
	0x064A: {0xFEF1, 0xFEF2, 0xFEF3, 0xFEF4, joinDual}, // Yeh
	0x0671: {0xFB50, 0xFB51, 0, 0, joinRight},          // Alef Wasla
	0x0677: {0xFBDD, 0, 0, 0, joinRight},               // U With Hamza Above
	0x0679: {0xFB66, 0xFB67, 0xFB68, 0xFB69, joinDual}, // Tteh
	0x067A: {0xFB5E, 0xFB5F, 0xFB60, 0xFB61, joinDual}, // Tteheh
	0x067B: {0xFB52, 0xFB53, 0xFB54, 0xFB55, joinDual}, // Beeh
	0x067E: {0xFB56, 0xFB57, 0xFB58, 0xFB59, joinDual}, // Peh
	0x067F: {0xFB62, 0xFB63, 0xFB64, 0xFB65, joinDual}, // Teheh
	0x0680: {0xFB5A, 0xFB5B, 0xFB5C, 0xFB5D, joinDual}, // Beheh
	0x0683: {0xFB76, 0xFB77, 0xFB78, 0xFB79, joinDual}, // Nyeh
	0x0684: {0xFB72, 0xFB73, 0xFB74, 0xFB75, joinDual}, // Dyeh
	0x0686: {0xFB7A, 0xFB7B, 0xFB7C, 0xFB7D, joinDual}, // Tcheh
	0x0687: {0xFB7E, 0xFB7F, 0xFB80, 0xFB81, joinDual}, // Tcheheh
	0x0688: {0xFB88, 0xFB89, 0, 0, joinRight},          // Ddal
	0x068C: {0xFB84, 0xFB85, 0, 0, joinRight},          // Dahal
	0x068D: {0xFB82, 0xFB83, 0, 0, joinRight},          // Ddahal
	0x068E: {0xFB86, 0xFB87, 0, 0, joinRight},          // Dul
	0x0691: {0xFB8C, 0xFB8D, 0, 0, joinRight},          // Rreh
	0x0698: {0xFB8A, 0xFB8B, 0, 0, joinRight},          // Jeh
	0x06A4: {0xFB6A, 0xFB6B, 0xFB6C, 0xFB6D, joinDual}, // Veh
	0x06A6: {0xFB6E, 0xFB6F, 0xFB70, 0xFB71, joinDual}, // Peheh
	0x06A9: {0xFB8E, 0xFB8F, 0xFB90, 0xFB91, joinDual}, // Keheh
	0x06AD: {0xFBD3, 0xFBD4, 0xFBD5, 0xFBD6, joinDual}, // Ng
	0x06AF: {0xFB92, 0xFB93, 0xFB94, 0xFB95, joinDual}, // Gaf
	0x06B1: {0xFB9A, 0xFB9B, 0xFB9C, 0xFB9D, joinDual}, // Ngoeh
	0x06B3: {0xFB96, 0xFB97, 0xFB98, 0xFB99, joinDual}, // Gueh
	0x06BA: {0xFB9E, 0xFB9F, 0, 0, joinRight},          // Noon Ghunna
	0x06BB: {0xFBA0, 0xFBA1, 0xFBA2, 0xFBA3, joinDual}, // Rnoon
	0x06BE: {0xFBAA, 0xFBAB, 0xFBAC, 0xFBAD, joinDual}, // Heh Doachashmee
	0x06C0: {0xFBA4, 0xFBA5, 0, 0, joinRight},          // Heh With Yeh Above
	0x06C1: {0xFBA6, 0xFBA7, 0xFBA8, 0xFBA9, joinDual}, // Heh Goal
	0x06C5: {0xFBE0, 0xFBE1, 0, 0, joinRight},          // Kirghiz Oe
	0x06C6: {0xFBD9, 0xFBDA, 0, 0, joinRight},          // Oe
	0x06C7: {0xFBD7, 0xFBD8, 0, 0, joinRight},          // U
	0x06C8: {0xFBDB, 0xFBDC, 0, 0, joinRight},          // Yu
	0x06C9: {0xFBE2, 0xFBE3, 0, 0, joinRight},          // Kirghiz Yu
	0x06CB: {0xFBDE, 0xFBDF, 0, 0, joinRight},          // Ve
	0x06CC: {0xFBFC, 0xFBFD, 0xFBFE, 0xFBFF, joinDual}, // Farsi Yeh
	0x06D0: {0xFBE4, 0xFBE5, 0xFBE6, 0xFBE7, joinDual}, // E
	0x06D2: {0xFBAE, 0xFBAF, 0, 0, joinRight},          // Yeh Barree
	0x06D3: {0xFBB0, 0xFBB1, 0, 0, joinRight},          // Yeh Barree With Hamza Above
}

// lamAlef holds the mandatory lam-alef ligatures.
//
// These are not an optional nicety. Arabic orthography requires lam followed by alef
// to be written as one joined shape, and setting the two letters side by side is as
// wrong as putting a space inside an English word. Unicode gives each ligature its
// own codepoint in the presentation-form block, so no glyph substitution table is
// needed to reach it.
var lamAlef = map[rune]struct{ isolated, final rune }{
	0x0622: {0xFEF5, 0xFEF6}, // lam + Alef With Madda Above
	0x0623: {0xFEF7, 0xFEF8}, // lam + Alef With Hamza Above
	0x0625: {0xFEF9, 0xFEFA}, // lam + Alef With Hamza Below
	0x0627: {0xFEFB, 0xFEFC}, // lam + Alef
}
